import {readdir,readFile,lstat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const hash=b=>createHash('sha256').update(b).digest('hex');
const manifest=JSON.parse(await readFile('config/production-models.json','utf8'));
const approved=new Map(Object.entries(manifest).map(([name,m])=>[m.sha256,name]));
const seen=new Set(),files=[];
async function scan(dir){for(const name of await readdir(dir)){const path=dir+'/'+name;const stat=await lstat(path);assert(!stat.isSymbolicLink(),`Symlink: ${path}`);if(stat.isDirectory()){assert(path==='dist/assets',`Unexpected directory: ${path}`);await scan(path);continue;}const rel=path.slice(5);assert(rel==='index.html'||/^assets\/[A-Za-z0-9_.-]+\.(js|css|glb)$/.test(rel),`Unexpected output: ${rel}`);const b=await readFile(path);const digest=hash(b);if(rel.endsWith('.glb')){assert(approved.has(digest),`Unapproved model: ${rel}`);seen.add(approved.get(digest));assert.equal(b.readUInt32LE(0),0x46546c67);const g=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert.equal(g.images?.length??0,0,'Expected vertex colors, no embedded photos');assert.equal(g.textures?.length??0,0);assert.equal(g.skins.length,1);assert.equal(g.skins[0].joints.length,46);for(const clip of ['IdleNorm','WalkCycle','IdleSit'])assert(g.animations.some(a=>a.name===clip));assert(g.meshes.some(m=>m.primitives.some(p=>p.attributes.COLOR_0!==undefined)));assert(!JSON.stringify(g).match(/file:\/|\/home\/|state\.npz|input\/|artifacts\//i));}else{const text=b.toString('utf8');assert(!/(?:input\/|artifacts\/|photo-review|external-cat-audit|state\.npz|__cat-preview|__cat-glb|\/home\/tomot|BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY|gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{30,}|AKIA[A-Z0-9]{16})/.test(text),`Private content marker: ${rel}`);if(rel==='index.html')for(const credit of ['DreamNoms','783fcb78b55b4394a212c2b6392e1113','creativecommons.org/licenses/by/4.0/','改変'])assert(text.includes(credit));}files.push({path:rel,bytes:b.length,sha256:digest});}}
await scan('dist');assert.equal(seen.size,2,'Exactly both approved cats required');console.log(JSON.stringify({passed:true,models:[...seen],files,totalBytes:files.reduce((n,f)=>n+f.bytes,0)},null,2));
