import {chromium} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE??'/';assert(/^\/[A-Za-z0-9_.-]*\/$/.test(base)||base==='/');
const label=base==='/'?'root':'subpath';const out='artifacts/production';await mkdir(out,{recursive:true});
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');assert(url.pathname.startsWith(base));const path=resolve('dist',decodeURIComponent(url.pathname.slice(base.length)||'index.html'));assert(path.startsWith(resolve('dist')+'/'));assert((await stat(path)).isFile());res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.glb':'model/gltf-binary'})[extname(path)]??'application/octet-stream');res.end(await readFile(path));}catch{res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const page=await browser.newPage({viewport:{width:960,height:720}});const errors=[],warnings=[],badResponses=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text())});page.on('response',r=>{if(r.status()>=400)badResponses.push({url:r.url(),status:r.status()})});page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));await page.route('**/*',r=>{requests.push(r.request().url());if(!r.request().url().startsWith(origin+base)){errors.push('Unexpected request '+r.request().url());return r.abort()}return r.continue()});await page.goto(origin+base);await page.waitForSelector('canvas[data-ready="true"]',{timeout:90000});assert.equal(await page.title(),'ぷーたんとこころのお部屋');await page.screenshot({path:`${out}/${label}-relax.png`,timeout:60000});const canvas=page.locator('canvas');const modes=[];
for(const [mode,labelText] of [['relax','のんびり過ごす'],['walk','ふたりでおさんぽ'],['sit','並んでおすわり']]){await page.getByRole('button',{name:labelText,exact:true}).click();assert.equal(await page.getByRole('button',{name:labelText,exact:true}).getAttribute('aria-pressed'),'true');const a=await canvas.screenshot({timeout:60000});await page.waitForTimeout(400);const b=await canvas.screenshot({timeout:60000});assert(!a.equals(b),mode+' must animate');modes.push({mode,frames_change:true});if(mode!=='relax')await page.screenshot({path:`${out}/${label}-${mode}.png`,timeout:60000});}
await page.getByRole('button',{name:'一時停止',exact:true}).click();await page.waitForTimeout(500);const stopped=await canvas.screenshot({timeout:60000});await page.waitForTimeout(300);assert(stopped.equals(await canvas.screenshot({timeout:60000})),'Pause must freeze');const box=await canvas.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.56,{steps:15});await page.mouse.up();await page.waitForTimeout(700);const rotated=await canvas.screenshot({timeout:60000});assert(!rotated.equals(stopped),'Drag must rotate');await page.mouse.wheel(0,-400);await page.waitForTimeout(700);assert(!rotated.equals(await canvas.screenshot({timeout:60000})),'Wheel must zoom');await page.getByRole('button',{name:'視点を戻す'}).click();assert((await page.locator('footer').innerText()).includes('DreamNoms'));assert(requests.filter(u=>u.endsWith('.glb')).length===2);assert.equal(errors.length,0,JSON.stringify(errors));assert.equal(badResponses.length,0,JSON.stringify(badResponses));await writeFile(`${out}/${label}-browser.json`,JSON.stringify({passed:true,base,modes,drag:true,zoom:true,pause:true,errors,warnings,badResponses,requests:requests.map(u=>u.replace(origin,''))},null,2));console.log(`${base}: both models, 3 modes, animation, drag, zoom, pause, credits, zero errors/404 passed`);}finally{await browser.close();await new Promise(r=>server.close(r));}
